name: Deploy Dev Images
on:
  push:
    branches: [ master ]

jobs:
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          access_token_lifetime: '300s'
          token_format: 'access_token'
          workload_identity_provider: 'projects/833678005979/locations/global/workloadIdentityPools/addr-pool/providers/github'
          service_account: 'addr-gh-actions@ujelly-dev.iam.gserviceaccount.com'

     
